W4D5/music_app_capybara/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bands
  resources :users
  resource :session, only:[:new,:create,:destroy]
end

W4D5/music_app_capybara/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: trued
end

W4D5/music_app_capybara/app/models/user.rb
class User < ApplicationRecord
    validates :password_digest, :email, :session_token, presence: true
    validates :email, uniqueness: true
    validates :password, length: { minimum: 6, allow_nil: true }
    before_validation :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end
    
    def self.generate_token
        SecureRandom::urlsafe_base64(16)
    end

    def reset_session_token!
        self.session_token = User.generate_token
        self.save!
        self.session_token
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    private
    def ensure_session_token
        self.session_token ||= User.generate_token
    end
end

W4D5/music_app_capybara/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        
        @current_user ||= User.find_by(session_token: session[:session_token])
    end
    
    def logged_in?
        !!current_user
    end
    
    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        current_user.reset_session_token! if current_user
        session[:session_token] = nil
    end

    # def require_login
    #     redirect_to new_session_url unless logged_in?
    # end

    # def require_logout
    #     redirect_to new_user_url if logged_in?
    # end
end

W4D5/music_app_capybara/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end
    
    def new
        @band = Band.new
        render :new
    end

    def create
        band = Band.new(band_params)
        if band.save
            render :index
        else
            render :new
        end
    end

    def edit
        band = Band.find(band_params)
        if band
            render :edit
        else
            render :create
        end
    end

    def show
        band = Band.find(band_params)
        if band
            render :show
        else
            render :index
        end
    end

    def update
    end

    def destroy
    end

    private
    def band_params
        params.require(:band).permit(:name)
    end
end

W4D5/music_app_capybara/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    # before_action :require_logout, only:[:new,:create]

    def new
        render :new
    end

    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if user
            login!(user)
            redirect_to user_url(user)
        else
            redirect_to new_session_url
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

W4D5/music_app_capybara/app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action :require_login, except:[:create]

    def index
        @users = User.all
        render :index
    end

    def new
        @user = User.new
        render :new
    end

    def create
        user = User.new(user_params)
        if user.save
            login!(user)
            redirect_to user_url(user)
        else
            redirect_to new_user_url
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

W4D5/music_app_capybara/app/helpers/bands_helper.rb
module BandsHelper
end

W4D5/music_app_capybara/app/helpers/session_helper.rb
module SessionHelper
end

W4D5/music_app_capybara/app/helpers/user_helper.rb
module UserHelper
end

W4D5/music_app_capybara/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  
    <% if logged_in? %>
      <a href= "<%= new_user_url %>" >Sign Up</a>
      <a href= "<%= new_session_url %>" >Sign In</a> 
      <h1>Welcome, <%= current_user.email %></h1>
      <form action=" <%= session_url %> " method="POST">
          <input type="hidden" name="_method" value="DELETE">
          <input type="hidden" name="authenticity_token" value="form_authenticity_token">
          <label for="logout">
              <input type="submit" value = "Log Out">
          </label>
      </form>    
    <% else %>
      <a href= "<%= new_user_url %>"    >Sign Up</a>
      <a href= "<%= new_session_url %>" >Sign In</a> 
    <% end %>
    
    <%= yield %>
  </body>
</html>

W4D5/music_app_capybara/app/views/users/new.html.erb
<h1>Welcome, new user</h1>

<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    
    <label for="email">Enter email address:
        <input type="text" name="user[email]" value = "<%= @user.email %>">
    </label>

    <label for="password">Enter password:
        <input type="password" name="user[password]">
    </label>

    <input type="submit" value = "Sign up!">

</form>

W4D5/music_app_capybara/app/views/users/show.html.erb
<p>Here goes band stuff</p>